version: '3.9'

services:
  backend:
    build: 
      context: ./Backend
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend/RO.FrontEnd
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge